### PR TITLE
Adding foreign keys for userId and codeId field

### PR DESCRIPTION
**Pull request by batflarrow**
Issue: 83

#### Short description of what this resolves:
Changed data type of codes array item field in user schema and userId field in codeSchema

#### Changes proposed in this pull request and/or Screenshots of changes:

- Added Foreign Key references in the fields
-
-

### CODE REVIEW

**Comment by batflarrow** [comment]
@aknsal Please review.

**Comment by aknsal** [comment]
You can update this in readme as well. Do not create another issue for that.

**Comment by batflarrow** [comment]
> You can update this in readme as well. Do not create another issue for that.

Yeah sure😂

**Comment by batflarrow** [comment]
@aknsal Updated readme as well, Let me know if anything else is required.

**Pull request merged**
